name: places
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2  
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.5  
  provider: ^6.0.4
  text_chunk_styling: ^2.0.2

dev_dependencies:
  dart_code_metrics: ^4.21.2
  flutter_test:
    sdk: flutter  
  surf_lint_rules: ^1.5.0

flutter:
  uses-material-design: true

  assets:
   - res/
   - res/icons/
   - res/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic